-- Generado por scripts/gen-seed-sql.mjs desde src/data/seed.json — NO editar a mano.
-- Idempotente: se puede ejecutar varias veces (on conflict do nothing).
begin;

insert into public.sites (name, slug) values ('Agroyauri SAC', 'agroyauri') on conflict (slug) do nothing;

insert into public.site_settings (site_id, key, value) values ((select id from public.sites where slug = 'agroyauri'), 'contact', '{"company":"AGROYAURI SAC","legal_name":"Agroyauri S.A.C.","phones":["931-637-047","991-554-666"],"whatsapp":"51931637047","email":"eyauri@agroyauri.com","city":"Pachacamac","region":"Lima","country":"PE","ruc":"20614909189","tagline":"Soluciones verdes para un mejor mañana."}'::jsonb) on conflict (site_id, key) do nothing;
insert into public.site_settings (site_id, key, value) values ((select id from public.sites where slug = 'agroyauri'), 'social', '{"facebook":"https://www.facebook.com/profile.php?id=61592788795207","tiktok":"https://www.tiktok.com/@agroyauri.com","youtube":"https://www.youtube.com/@agroyauri","linkedin":""}'::jsonb) on conflict (site_id, key) do nothing;
insert into public.site_settings (site_id, key, value) values ((select id from public.sites where slug = 'agroyauri'), 'plans', '{"title":"Inversión en un entorno mejor","note":"* Precios referenciales. El costo final depende del área, el estado del terreno y el alcance del servicio; te enviamos una cotización exacta tras la visita técnica.","items":[{"name":"Plan Básico","subtitle":"Mantenimiento de Áreas Verdes","icon":"leaf","price":450,"price_label":"/mes","show_price":true,"featured":false,"features":["Mantenimiento de áreas verdes","Poda y limpieza","Control básico de plagas","Reporte fotográfico"]},{"name":"Plan Estándar","subtitle":"Paisajismo + Riego","icon":"leaf","price":2500,"price_label":"desde","show_price":true,"featured":true,"features":["Diseño de áreas verdes","Instalación de riego tecnificado","Mantenimiento mensual","Asesoría personalizada"]},{"name":"Plan Premium","subtitle":"Paisajismo Integral","icon":"gear","price":5000,"price_label":"desde","show_price":true,"featured":false,"features":["Paisajismo y decoración","Sistema de riego automatizado","Control de plagas y saneamiento","Mantenimiento continuo"]}]}'::jsonb) on conflict (site_id, key) do nothing;

insert into public.categories (site_id, name, slug, sort_order) values ((select id from public.sites where slug = 'agroyauri'), 'Insumos agrícolas', 'insumos-agricolas', 1) on conflict (site_id, slug) do nothing;
insert into public.categories (site_id, name, slug, sort_order) values ((select id from public.sites where slug = 'agroyauri'), 'Plantas ornamentales', 'plantas-ornamentales', 2) on conflict (site_id, slug) do nothing;

insert into public.services (site_id, name, slug, short_description, description, image_url, icon, price_type, price_from, price_unit, show_price, show_in_home, sort_order, is_active, seo_title, seo_description) values ((select id from public.sites where slug = 'agroyauri'), 'Paisajismo y áreas verdes', 'paisajismo-lima', 'Diseño, implementación y mantenimiento de jardines y áreas verdes.', 'Diseñamos e implementamos jardines y áreas verdes para viviendas, condominios y empresas en Lima. Trabajamos cada espacio según su uso, su tamaño y el estilo que busca el cliente, para lograr entornos saludables, productivos y visualmente atractivos.

## Qué incluye

- Diseño de áreas verdes y propuesta de paisajismo.
- Preparación del terreno e instalación de tierra de chacra.
- Instalación de grass americano.
- Plantación de especies ornamentales, arbustos y palmeras.
- Decoración de jardines con caminos, bordes y composiciones de plantas.

## Para quién es

Para familias que quieren renovar su jardín, condominios que necesitan áreas comunes cuidadas y empresas que buscan espacios verdes en sus instalaciones, como plantas industriales u oficinas.', '/media/services/paisajismo.jpg', 'paisajismo', 'quote', null, null, false, true, 1, true, 'Empresa de Paisajismo y Áreas Verdes en Lima | Agroyauri', 'Diseño e implementación de jardines y áreas verdes en Lima para viviendas, condominios y empresas. Instalación de grass, tierra de chacra y plantas ornamentales.') on conflict (site_id, slug) do nothing;
insert into public.services (site_id, name, slug, short_description, description, image_url, icon, price_type, price_from, price_unit, show_price, show_in_home, sort_order, is_active, seo_title, seo_description) values ((select id from public.sites where slug = 'agroyauri'), 'Mantenimiento de áreas verdes', 'mantenimiento-areas-verdes-lima', 'Mantenimiento periódico de jardines, condominios y áreas verdes empresariales.', 'Mantenemos jardines y áreas verdes para que se conserven sanos y ordenados durante todo el año. Atendemos viviendas, condominios y empresas en Lima con visitas programadas.

## Qué incluye

- Corte de césped y limpieza de áreas verdes.
- Poda y renovación de árboles y arbustos.
- Aplicación de abono orgánico y fertilizantes.
- Recuperación de áreas verdes deterioradas.
- Control de plagas preventivo.

## Experiencia

Hemos realizado mantenimiento de condominios en La Molina, recuperación de áreas verdes en La Planicie y renovación de árboles para empresas.', '/media/services/mantenimiento.jpg', 'mantenimiento', 'quote', null, null, false, false, 2, true, 'Mantenimiento de Áreas Verdes y Jardines en Lima | Agroyauri', 'Mantenimiento de jardines y áreas verdes en Lima: corte de césped, poda, abonado, recuperación de áreas verdes y control de plagas para casas, condominios y empresas.') on conflict (site_id, slug) do nothing;
insert into public.services (site_id, name, slug, short_description, description, image_url, icon, price_type, price_from, price_unit, show_price, show_in_home, sort_order, is_active, seo_title, seo_description) values ((select id from public.sites where slug = 'agroyauri'), 'Sistemas de riego tecnificado', 'riego-tecnificado-lima', 'Soluciones eficientes de riego para un uso óptimo del agua.', 'Instalamos sistemas de riego tecnificado y automatizado que distribuyen el agua de forma uniforme y reducen el desperdicio. Un buen sistema de riego ahorra tiempo de mantenimiento y mantiene el césped y las plantas en buen estado.

## Qué incluye

- Evaluación del área y diseño del sistema de riego.
- Instalación de tuberías, válvulas y aspersores.
- Riego automatizado con programación de horarios.
- Integración con el diseño de paisajismo.

## Proyecto de referencia

Instalamos un sistema de riego automatizado en La Planicie, La Molina.', '/media/services/riego.jpg', 'riego', 'quote', null, null, false, true, 3, true, 'Sistemas de Riego Tecnificado y Automatizado en Lima | Agroyauri', 'Instalación de sistemas de riego tecnificado y automatizado en Lima para jardines y áreas verdes. Uso eficiente del agua con aspersores y programación.') on conflict (site_id, slug) do nothing;
insert into public.services (site_id, name, slug, short_description, description, image_url, icon, price_type, price_from, price_unit, show_price, show_in_home, sort_order, is_active, seo_title, seo_description) values ((select id from public.sites where slug = 'agroyauri'), 'Fumigación y control de plagas', 'fumigacion-control-plagas-lima', 'Ambientes libres de plagas en hogares, empresas y condominios.', 'Realizamos fumigación y control de plagas en jardines, viviendas, condominios, empresas y fundos. Aplicamos los productos adecuados para cada caso, con personal equipado y protegido.

## Qué incluye

- Evaluación del tipo de plaga y del área afectada.
- Fumigación de jardines y áreas verdes.
- Control de plagas en condominios y fundos.
- Recomendaciones para prevenir nuevas infestaciones.

## Proyecto de referencia

Hemos realizado fumigaciones de plagas en condominios y fundos.', '/media/services/fumigacion.jpg', 'plagas', 'quote', null, null, false, true, 4, true, 'Fumigación y Control de Plagas en Lima | Agroyauri', 'Fumigación y control de plagas en Lima para jardines, hogares, condominios, empresas y fundos. Personal equipado y productos adecuados para cada caso.') on conflict (site_id, slug) do nothing;
insert into public.services (site_id, name, slug, short_description, description, image_url, icon, price_type, price_from, price_unit, show_price, show_in_home, sort_order, is_active, seo_title, seo_description) values ((select id from public.sites where slug = 'agroyauri'), 'Saneamiento ambiental', 'saneamiento-ambiental', 'Desinfección y control sanitario para un entorno más saludable.', 'Brindamos servicios de saneamiento ambiental para mantener espacios limpios y saludables en viviendas, condominios y empresas.

## Qué incluye

- Desinfección de ambientes y áreas exteriores.
- Nebulización.
- Control sanitario complementario al control de plagas.

Cuéntanos qué necesitas y te enviamos una propuesta adaptada a tu espacio.', '/media/services/saneamiento.jpg', 'saneamiento', 'quote', null, null, false, true, 5, true, 'Saneamiento Ambiental y Desinfección en Lima | Agroyauri', 'Saneamiento ambiental en Lima: desinfección, nebulización y control sanitario para viviendas, condominios y empresas.') on conflict (site_id, slug) do nothing;
insert into public.services (site_id, name, slug, short_description, description, image_url, icon, price_type, price_from, price_unit, show_price, show_in_home, sort_order, is_active, seo_title, seo_description) values ((select id from public.sites where slug = 'agroyauri'), 'Insumos agrícolas', 'insumos-agricolas', 'Venta de fertilizantes, plaguicidas y productos de alta calidad.', 'Comercializamos insumos agrícolas de alta calidad para el cuidado de jardines, áreas verdes y cultivos: fertilizantes, plaguicidas, abono orgánico y tierra de chacra.

Revisa nuestro catálogo de productos y consúltanos por WhatsApp la disponibilidad y el precio.', '/media/services/insumos.jpg', 'insumos', 'quote', null, null, false, true, 6, true, 'Venta de Insumos Agrícolas, Fertilizantes y Plaguicidas | Agroyauri', 'Venta de insumos agrícolas en Lima: fertilizantes, plaguicidas, abono orgánico y tierra de chacra para jardines, áreas verdes y cultivos.') on conflict (site_id, slug) do nothing;
insert into public.services (site_id, name, slug, short_description, description, image_url, icon, price_type, price_from, price_unit, show_price, show_in_home, sort_order, is_active, seo_title, seo_description) values ((select id from public.sites where slug = 'agroyauri'), 'Plantas ornamentales', 'plantas-ornamentales', 'Variedad de plantas y mantenimiento para embellecer tus espacios.', 'Ofrecemos plantas ornamentales, arbustos y palmeras para jardines, terrazas y áreas verdes, además de su plantación y mantenimiento.

## Qué incluye

- Venta de plantas ornamentales y arbustos.
- Asesoría para elegir especies según el espacio.
- Plantación y mantenimiento.', '/media/services/plantas.jpg', 'plantas', 'quote', null, null, false, true, 7, true, 'Plantas Ornamentales para Jardines en Lima | Agroyauri', 'Plantas ornamentales, arbustos y palmeras para jardines y áreas verdes en Lima, con asesoría, plantación y mantenimiento.') on conflict (site_id, slug) do nothing;

insert into public.projects (site_id, title, slug, client, location, short_description, description, featured_image, gallery, before_image, after_image, is_featured, is_published, sort_order, seo_title, seo_description, service_id) values ((select id from public.sites where slug = 'agroyauri'), 'Instalación de grass americano', 'instalacion-grass-americano', null, null, 'Preparación del terreno e instalación de grass americano en área verde con piscina.', 'Preparamos el terreno e instalamos grass americano para formar un área verde uniforme alrededor de la piscina.', '/media/projects/instalacion-grass-americano/01.jpg', array['/media/projects/instalacion-grass-americano/01.jpg', '/media/projects/instalacion-grass-americano/02.jpg', '/media/projects/instalacion-grass-americano/03.jpg']::text[], null, null, true, true, 1, null, null, (select id from public.services where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'paisajismo-lima')) on conflict (site_id, slug) do nothing;
insert into public.projects (site_id, title, slug, client, location, short_description, description, featured_image, gallery, before_image, after_image, is_featured, is_published, sort_order, seo_title, seo_description, service_id) values ((select id from public.sites where slug = 'agroyauri'), 'Sistema de riego automatizado', 'riego-automatizado-la-planicie-la-molina', null, 'La Planicie – La Molina', 'Instalación de un sistema de riego automatizado en La Planicie, La Molina.', 'Instalamos un sistema de riego automatizado: zanjas, tuberías, válvulas y aspersores, para mantener el jardín regado de forma uniforme y eficiente.', '/media/projects/riego-automatizado-la-planicie-la-molina/01.jpg', array['/media/projects/riego-automatizado-la-planicie-la-molina/01.jpg', '/media/projects/riego-automatizado-la-planicie-la-molina/02.jpg', '/media/projects/riego-automatizado-la-planicie-la-molina/03.jpg', '/media/projects/riego-automatizado-la-planicie-la-molina/04.jpg']::text[], null, null, true, true, 2, null, null, (select id from public.services where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'riego-tecnificado-lima')) on conflict (site_id, slug) do nothing;
insert into public.projects (site_id, title, slug, client, location, short_description, description, featured_image, gallery, before_image, after_image, is_featured, is_published, sort_order, seo_title, seo_description, service_id) values ((select id from public.sites where slug = 'agroyauri'), 'Fumigación de plagas', 'fumigacion-plagas-condominios-fundos', 'Condominios y fundos', null, 'Fumigación de plagas en jardines de condominios y fundos.', 'Realizamos fumigaciones de plagas en jardines y áreas verdes de condominios y fundos, con personal equipado y protegido.', '/media/projects/fumigacion-plagas-condominios-fundos/01.jpg', array['/media/projects/fumigacion-plagas-condominios-fundos/01.jpg', '/media/projects/fumigacion-plagas-condominios-fundos/02.jpg', '/media/projects/fumigacion-plagas-condominios-fundos/03.jpg', '/media/projects/fumigacion-plagas-condominios-fundos/04.jpg']::text[], null, null, true, true, 3, null, null, (select id from public.services where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'fumigacion-control-plagas-lima')) on conflict (site_id, slug) do nothing;
insert into public.projects (site_id, title, slug, client, location, short_description, description, featured_image, gallery, before_image, after_image, is_featured, is_published, sort_order, seo_title, seo_description, service_id) values ((select id from public.sites where slug = 'agroyauri'), 'Paisajismo y decoración', 'paisajismo-decoracion-granos-verdes', 'Empresa Granos Verdes SAC', null, 'Proyecto de paisajismo y decoración para la empresa Granos Verdes SAC.', 'Proyecto de paisajismo y decoración de áreas verdes para la empresa Granos Verdes SAC: composición de arbustos, césped y caminos.', '/media/projects/paisajismo-decoracion-granos-verdes/01.jpg', array['/media/projects/paisajismo-decoracion-granos-verdes/01.jpg', '/media/projects/paisajismo-decoracion-granos-verdes/02.jpg', '/media/projects/paisajismo-decoracion-granos-verdes/03.jpg', '/media/projects/paisajismo-decoracion-granos-verdes/04.jpg']::text[], null, null, true, true, 4, null, null, (select id from public.services where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'paisajismo-lima')) on conflict (site_id, slug) do nothing;
insert into public.projects (site_id, title, slug, client, location, short_description, description, featured_image, gallery, before_image, after_image, is_featured, is_published, sort_order, seo_title, seo_description, service_id) values ((select id from public.sites where slug = 'agroyauri'), 'Recuperación de áreas verdes', 'recuperacion-areas-verdes-la-molina', 'Casa Familia Romero', 'Urb. La Planicie – La Molina', 'Recuperación de áreas verdes deterioradas en una vivienda de La Planicie, La Molina.', 'Recuperamos las áreas verdes de una vivienda en la Urb. La Planicie, La Molina. Las fotos muestran el estado del jardín antes y después del trabajo.', '/media/projects/recuperacion-areas-verdes-la-molina/01.jpg', array['/media/projects/recuperacion-areas-verdes-la-molina/01.jpg', '/media/projects/recuperacion-areas-verdes-la-molina/02.jpg', '/media/projects/recuperacion-areas-verdes-la-molina/03.jpg', '/media/projects/recuperacion-areas-verdes-la-molina/04.jpg', '/media/projects/recuperacion-areas-verdes-la-molina/05.jpg', '/media/projects/recuperacion-areas-verdes-la-molina/06.jpg', '/media/projects/recuperacion-areas-verdes-la-molina/07.jpg', '/media/projects/recuperacion-areas-verdes-la-molina/08.jpg', '/media/projects/recuperacion-areas-verdes-la-molina/09.jpg', '/media/projects/recuperacion-areas-verdes-la-molina/10.jpg', '/media/projects/recuperacion-areas-verdes-la-molina/11.jpg']::text[], '/media/projects/recuperacion-areas-verdes-la-molina/10.jpg', '/media/projects/recuperacion-areas-verdes-la-molina/01.jpg', true, true, 5, null, null, (select id from public.services where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'mantenimiento-areas-verdes-lima')) on conflict (site_id, slug) do nothing;
insert into public.projects (site_id, title, slug, client, location, short_description, description, featured_image, gallery, before_image, after_image, is_featured, is_published, sort_order, seo_title, seo_description, service_id) values ((select id from public.sites where slug = 'agroyauri'), 'Instalación de tierra de chacra', 'instalacion-tierra-chacra-grupo-silvestre', 'Grupo Silvestre', 'Planta industrial', 'Instalación de tierra de chacra para área verde en la planta industrial de Grupo Silvestre.', 'Instalamos tierra de chacra para preparar el área verde de la planta industrial de la empresa Grupo Silvestre.', '/media/projects/instalacion-tierra-chacra-grupo-silvestre/01.jpg', array['/media/projects/instalacion-tierra-chacra-grupo-silvestre/01.jpg', '/media/projects/instalacion-tierra-chacra-grupo-silvestre/02.jpg', '/media/projects/instalacion-tierra-chacra-grupo-silvestre/03.jpg']::text[], null, null, true, true, 6, null, null, (select id from public.services where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'paisajismo-lima')) on conflict (site_id, slug) do nothing;
insert into public.projects (site_id, title, slug, client, location, short_description, description, featured_image, gallery, before_image, after_image, is_featured, is_published, sort_order, seo_title, seo_description, service_id) values ((select id from public.sites where slug = 'agroyauri'), 'Mantenimiento de condominio', 'mantenimiento-condominio-town-houses-la-molina', 'Town Houses', 'La Molina', 'Mantenimiento de áreas verdes del condominio Town Houses en La Molina.', 'Mantenimiento de las áreas verdes del condominio Town Houses en La Molina: corte de césped, poda y fumigación.', '/media/projects/mantenimiento-condominio-town-houses-la-molina/01.jpg', array['/media/projects/mantenimiento-condominio-town-houses-la-molina/01.jpg', '/media/projects/mantenimiento-condominio-town-houses-la-molina/02.jpg', '/media/projects/mantenimiento-condominio-town-houses-la-molina/03.jpg', '/media/projects/mantenimiento-condominio-town-houses-la-molina/04.jpg', '/media/projects/mantenimiento-condominio-town-houses-la-molina/05.jpg', '/media/projects/mantenimiento-condominio-town-houses-la-molina/06.jpg']::text[], null, null, false, true, 7, null, null, (select id from public.services where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'mantenimiento-areas-verdes-lima')) on conflict (site_id, slug) do nothing;
insert into public.projects (site_id, title, slug, client, location, short_description, description, featured_image, gallery, before_image, after_image, is_featured, is_published, sort_order, seo_title, seo_description, service_id) values ((select id from public.sites where slug = 'agroyauri'), 'Renovación de árboles', 'renovacion-arboles-sepin', 'Empresa Sepin SAC', null, 'Renovación y poda de árboles para la empresa Sepin SAC.', 'Renovación y poda de árboles y palmeras en las áreas verdes de la empresa Sepin SAC.', '/media/projects/renovacion-arboles-sepin/01.jpg', array['/media/projects/renovacion-arboles-sepin/01.jpg', '/media/projects/renovacion-arboles-sepin/02.jpg', '/media/projects/renovacion-arboles-sepin/03.jpg', '/media/projects/renovacion-arboles-sepin/04.jpg', '/media/projects/renovacion-arboles-sepin/05.jpg']::text[], null, null, false, true, 8, null, null, (select id from public.services where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'mantenimiento-areas-verdes-lima')) on conflict (site_id, slug) do nothing;
insert into public.projects (site_id, title, slug, client, location, short_description, description, featured_image, gallery, before_image, after_image, is_featured, is_published, sort_order, seo_title, seo_description, service_id) values ((select id from public.sites where slug = 'agroyauri'), 'Aplicación de abono orgánico', 'aplicacion-abono-organico', null, null, 'Aplicación de abono orgánico para mejorar el suelo de un área verde.', 'Aplicación de abono orgánico en un área verde para mejorar el suelo y el crecimiento del césped.', '/media/projects/aplicacion-abono-organico/01.jpg', array['/media/projects/aplicacion-abono-organico/01.jpg', '/media/projects/aplicacion-abono-organico/02.jpg', '/media/projects/aplicacion-abono-organico/03.jpg']::text[], null, null, false, true, 9, null, null, (select id from public.services where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'mantenimiento-areas-verdes-lima')) on conflict (site_id, slug) do nothing;

insert into public.products (site_id, name, slug, description, image_url, price, price_unit, show_price, available, featured, is_published, sort_order, seo_title, seo_description, category_id) values ((select id from public.sites where slug = 'agroyauri'), 'Fertilizantes y plaguicidas', 'fertilizantes-plaguicidas', 'Venta de fertilizantes y plaguicidas para el cuidado de jardines, áreas verdes y cultivos. Consúltanos por el producto que necesitas.', '/media/products/plaguicidas-fungicidas.jpg', null, null, false, true, true, true, 1, null, null, (select id from public.categories where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'insumos-agricolas')) on conflict (site_id, slug) do nothing;
insert into public.products (site_id, name, slug, description, image_url, price, price_unit, show_price, available, featured, is_published, sort_order, seo_title, seo_description, category_id) values ((select id from public.sites where slug = 'agroyauri'), 'Abono orgánico', 'abono-organico', 'Abono orgánico para mejorar el suelo de jardines y áreas verdes. También realizamos su aplicación.', '/media/products/abono-organico.jpg', null, null, false, true, true, true, 2, null, null, (select id from public.categories where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'insumos-agricolas')) on conflict (site_id, slug) do nothing;
insert into public.products (site_id, name, slug, description, image_url, price, price_unit, show_price, available, featured, is_published, sort_order, seo_title, seo_description, category_id) values ((select id from public.sites where slug = 'agroyauri'), 'Tierra de chacra', 'tierra-de-chacra', 'Tierra de chacra para preparar e instalar áreas verdes. Consulta volúmenes e instalación.', '/media/products/tierra-de-chacra.jpg', null, null, false, true, false, true, 3, null, null, (select id from public.categories where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'insumos-agricolas')) on conflict (site_id, slug) do nothing;
insert into public.products (site_id, name, slug, description, image_url, price, price_unit, show_price, available, featured, is_published, sort_order, seo_title, seo_description, category_id) values ((select id from public.sites where slug = 'agroyauri'), 'Plantas ornamentales', 'plantas-ornamentales', 'Variedad de plantas ornamentales para jardines, terrazas y áreas verdes.', '/media/products/plantas-ornamentales.jpg', null, null, false, true, true, true, 4, null, null, (select id from public.categories where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'plantas-ornamentales')) on conflict (site_id, slug) do nothing;
insert into public.products (site_id, name, slug, description, image_url, price, price_unit, show_price, available, featured, is_published, sort_order, seo_title, seo_description, category_id) values ((select id from public.sites where slug = 'agroyauri'), 'Arbustos ornamentales', 'arbustos-ornamentales', 'Arbustos para bordes, composiciones y decoración de jardines.', '/media/products/arbustos-ornamentales.jpg', null, null, false, true, false, true, 5, null, null, (select id from public.categories where site_id = (select id from public.sites where slug = 'agroyauri') and slug = 'plantas-ornamentales')) on conflict (site_id, slug) do nothing;

insert into public.blog_posts (site_id, title, slug, excerpt, content, featured_image, author, published_at, is_published, seo_title, seo_description) values ((select id from public.sites where slug = 'agroyauri'), 'Artículo de ejemplo (borrador)', 'articulo-de-ejemplo', 'Este es un borrador de ejemplo para probar el blog. Edítalo o elimínalo desde el panel.', 'Este es un **borrador** de ejemplo. No se publica en la web hasta que lo marques como publicado desde /admin.

## Subtítulo

Escribe aquí el contenido del artículo usando Markdown.', null, 'AGROYAURI SAC', null, false, null, null) on conflict (site_id, slug) do nothing;

insert into public.redirects (site_id, from_path, to_path) values ((select id from public.sites where slug = 'agroyauri'), '/servicios/fumigacion-lima', '/servicios/fumigacion-control-plagas-lima') on conflict (site_id, from_path) do nothing;
insert into public.redirects (site_id, from_path, to_path) values ((select id from public.sites where slug = 'agroyauri'), '/servicios/control-plagas-lima', '/servicios/fumigacion-control-plagas-lima') on conflict (site_id, from_path) do nothing;

commit;
